export const videoAction = {
  GET_VIDEOS_LIST: 'GET_VIDEOS_LIST',
  GET_VIDEOS_LIST_SUCCESS: 'GET_VIDEOS_LIST_SUCCESS',
  GET_VIDEOS_LIST_FAILURE: 'GET_VIDEOS_LIST_FAILURE',
  SAVE_VIDEOS_LIST: 'SAVE_VIDEOS_LIST',
  SAVE_VIDEOS_LIST_SUCCESS: 'SAVE_VIDEOS_LIST_SUCCESS',
  SAVE_VIDEOS_LIST_FAILURE: 'SAVE_VIDEOS_LIST_FAILURE',
  GET_VIDEO: 'GET_VIDEO',
};

export const songAction = {
  GET_ALL_SONGS_LIST: 'GET_ALL_SONGS_LIST',
  GET_ALL_SONGS_LIST_SUCCESS: 'GET_ALL_SONGS_LIST_SUCCESS',
  GET_ALL_SONGS_LIST_FAILURE: 'GET_ALL_SONGS_LIST_FAILURE',
  GET_ON_DEVICE_SONGS_LIST: 'GET_ON_DEVICE_SONGS_LIST',
  GET_ON_DEVICE_SONGS_LIST_SUCCESS: 'GET_ON_DEVICE_SONGS_LIST_SUCCESS',
  GET_ON_DEVICE_SONGS_LIST_FAILURE: 'GET_ON_DEVICE_SONGS_LIST_FAILURE',
};

export const authAction = {
  ON_LOGIN_GG: 'ON_LOGIN_GG',
  ON_LOGIN_GG_SUCCESS: 'ON_LOGIN_GG_SUCCESS',
  ON_LOGIN_GG_FAILURE: 'ON_LOGIN_GG_FAILURE',
  LOAD_AUTH: 'LOAD_AUTH',
  LOAD_AUTH_SUCCESS: 'LOAD_AUTH_SUCCESS',
  LOAD_AUTH_FAILURE: 'LOAD_AUTH_FAILURE',
  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  ON_LOGOUT_GG: 'ON_LOGOUT_GG',
  ON_LOGOUT_GG_SUCCESS: 'ON_LOGOUT_GG_SUCCESS',
  ON_LOGOUT_GG_FAILURE: 'ON_LOGOUT_GG_FAILURE',
};
